before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/aws-signing-proxy/main.go
    id: "aws-signing-proxy"
    env:
      - CGO_ENABLED=0
    binary: aws-signing-proxy
    goarch:
      - amd64
    goos:
      - linux
      - darwin
      - windows
  - main: ./cmd/vault-env-cred-provider/main.go
    id: "vault-env-cred-provider"
    env:
      - CGO_ENABLED=0
    binary: vault-env-cred-provider
    goarch:
      - amd64
    goos:
      - linux
      - darwin
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
