name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Build & push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: idealo/aws-signing-proxy
          tag_with_ref: true
